---

- name: (ansible_tools) ensure output directory exists
  file:
    path: "{{ ansible_tools_cmdb_dir | default('/var/www/html') }}"
    owner: "{{ ansible_tools_cmdb_dir_owner | default('ansible') }}"
    mode: "{{ ansible_tools_cmdb_dir_mode | default('0755') }}"
    group: "{{ ansible_tools_cmdb_dir_group | default('ansible') }}"
    state: directory
  become: yes

- name: (ansible_tools) execute awx-facts2cmdb
  shell: >
    INDEX_UPDATE={{ ansible_tools_cmdb_index_update | default('0') }}
    INDEX_ONLY={{ ansible_tools_cmdb_index_only | default('0') }}
    CMDB_TITLE="{{ ansible_tools_cmdb_title | default('CMDB') }}"
    CMDB_GROUP_LABEL="{{ ansible_tools_cmdb_group_label | default('group') }}"
    CMDB_GROUP_DESC="{{ ansible_tools_cmdb_group_description | default('description') }}"
    {{ ansible_tools_dir | default('/opt/ansible_tools') }}/awx-facts2cmdb
    {{ item }}
    {{ ansible_tools_cmdb_group | default('.*') }}
    {{ ansible_tools_cmdb_host | default('.*') }}
  args:
    executable: /bin/bash
  environment: "{{ ansible_tools_http_proxy_env }}"
  become: yes
  become_user: "{{ ansible_tools_user_username | default('ansible') }}"
  loop: "{{ ansible_tools_cmdb_inventories }}"
  when:
    - ansible_tools_cmdb_inventories is defined
    - ansible_tools_cmdb_inventories | length > 0
