---

- name: (ansible_tools) ensure output CMDB directories exists
  file:
    path: "{{ item }}"
    owner: "{{ ansible_tools_cmdb_dir_owner | default('ansible') }}"
    mode: "{{ ansible_tools_cmdb_dir_mode | default('0755') }}"
    group: "{{ ansible_tools_cmdb_dir_group | default('ansible') }}"
    state: directory
  become: yes
  loop: "{{ ansible_tools_cmdb_directories }}"
  when:
    - ansible_tools_cmdb_directories is defined
    - ansible_tools_cmdb_directories | length > 0

- name: (ansible_tools) copy CMDB templates
  template:
    src: ../templates/cmdb/{{ item }}
    dest: "{{ ansible_tools_cmdb_template_dir | default('/home/ansible') }}"
    owner: "{{ ansible_tools_cmdb_dir_owner | default('ansible') }}"
    mode: "{{ ansible_tools_cmdb_dir_mode | default('0755') }}"
    group: "{{ ansible_tools_cmdb_dir_group | default('ansible') }}"
  become: yes
  become_user: "{{ ansible_tools_user_username }}"
  loop: "{{ ansible_tools_cmdb_template_files }}"
  when:
    - ansible_tools_cmdb_template is defined
    - ansible_tools_cmdb_template | bool
    - ansible_tools_cmdb_template_files is defined
    - ansible_tools_cmdb_template_files | length > 0

- name: (ansible_tools) copy CMDB static images files
  template:
    src: ../templates/cmdb/static/images/{{ item }}
    dest: "{{ ansible_tools_cmdb_static_images_dir | default('/var/www/html/static/images') }}"
    owner: "{{ ansible_tools_cmdb_dir_owner | default('ansible') }}"
    mode: "{{ ansible_tools_cmdb_dir_mode | default('0755') }}"
    group: "{{ ansible_tools_cmdb_dir_group | default('ansible') }}"
  become: yes
  become_user: "{{ ansible_tools_user_username }}"
  loop: "{{ ansible_tools_cmdb_static_images_files }}"
  when:
    - ansible_tools_cmdb_static_images is defined
    - ansible_tools_cmdb_static_images | bool
    - ansible_tools_cmdb_static_images_files is defined
    - ansible_tools_cmdb_static_images_files | length > 0

- name: (ansible_tools) copy CMDB static js files
  template:
    src: ../templates/cmdb/static/js/{{ item }}
    dest: "{{ ansible_tools_cmdb_static_js_dir | default('/var/www/html/static/js') }}"
    owner: "{{ ansible_tools_cmdb_dir_owner | default('ansible') }}"
    mode: "{{ ansible_tools_cmdb_dir_mode | default('0755') }}"
    group: "{{ ansible_tools_cmdb_dir_group | default('ansible') }}"
  become: yes
  become_user: "{{ ansible_tools_user_username }}"
  loop: "{{ ansible_tools_cmdb_static_js_files }}"
  when:
    - ansible_tools_cmdb_static_js is defined
    - ansible_tools_cmdb_static_js | bool
    - ansible_tools_cmdb_static_js_files is defined
    - ansible_tools_cmdb_static_js_files | length > 0

- name: (ansible_tools) execute awx-facts2cmdb
  shell: >
    BASH_DEBUG={{ ansible_tools_bash_debug | default('0') }}
    INDEX_UPDATE={{ ansible_tools_cmdb_index_update | default('0') }}
    INDEX_ONLY={{ ansible_tools_cmdb_index_only | default('0') }}
    CMDB_TITLE="{{ ansible_tools_cmdb_tpl_title | default('CMDB') }}"
    CMDB_GROUP_LABEL="{{ ansible_tools_cmdb_tpl_group_label | default('group') }}"
    CMDB_GROUP_DESC="{{ ansible_tools_cmdb_tpl_group_description | default('description') }}"
    {{ ansible_tools_dir | default('/opt/ansible_tools') }}/awx-facts2cmdb
    {{ item }}
    {{ ansible_tools_cmdb_group | default('.*') }}
    {{ ansible_tools_cmdb_host | default('.*') }}
  environment: "{{ ansible_tools_http_proxy_env }}"
  become: yes
  become_user: "{{ ansible_tools_user_username | default('ansible') }}"
  loop: "{{ ansible_tools_cmdb_inventories }}"
  when:
    - ansible_tools_cmdb_inventories is defined
    - ansible_tools_cmdb_inventories | length > 0
