---

#- name: (ansible_tools) include OS family variables
#  include_vars: "{{ ansible_os_family }}.yml"

- name: (ansible_tools) include OS distribution variables
  include_vars: "{{ ansible_os_family }}_{{ ansible_distribution_major_version }}.yml"

- name: (ansible_tools) include user tasks
  include_tasks: user.yml
  when:
    - ansible_tools_user is defined
    - ansible_tools_user is defined | bool

- name: (ansible_tools) include proxy tasks
  include_tasks: proxy.yml
  when:
    - ansible_tools_http_proxy is defined
    - ansible_tools_http_proxy | bool

- name: (ansible_tools) include packages tasks
  include_tasks: packages.yml
  when:
    - ansible_tools_packages_install is defined
    - ansible_tools_packages_install | bool

- name: (ansible_tools) include pip tasks
  include_tasks: pip.yml
  when:
    - ansible_tools_pip_install is defined
    - ansible_tools_pip_install | bool

- name: (ansible_tools) include git tasks
  include_tasks: git.yml
  when:
    - ansible_tools_git_clone is defined
    - ansible_tools_git_clone | bool

- name: (ansible_tools) include permissions tasks
  include_tasks: permissions.yml
  when:
    - ansible_tools_permissions is defined
    - ansible_tools_permissions | bool

- name: (ansible_tools) include config tasks
  include_tasks: config.yml
  when:
    - ansible_tools_config is defined
    - ansible_tools_config | bool

- name: (ansible_tools) include cmdb tasks
  include_tasks: cmdb.yml
  when:
    - ansible_tools_cmdb is defined
    - ansible_tools_cmdb | bool
